### PR TITLE
remove empty characters from seeds.csv

### LINKED ISSUE #39: My bug in CSV import for seeds.rb
I made a bug!

I can't figure it out...still researching. But I just noticed that my CSV import which I was using for seed data in seeds.rb for some cryptic reason isn't getting the first element of each row. Here is the code:

```ruby
csv = CSV.parse(File.read(Rails.root.join('db', 'seeds.csv')), headers: true)

csv.each do |row|
  fap = FoodAccessPoint.new
  fap.address = row["address"]
  fap.town = row["town"]
  fap.state = row["state"]
  fap.zip = row["zip"]
  fap.name = row["name"]
  fap.phone_number = row["phone_number"]
  fap.website = row["website"]
  fap.website = "http://cnn.com" unless !fap.website.blank?
  fap.save
  puts fap.name + " saved." 
end
```

So whatever column is first in the seeds.csv file, it is not getting pulled in......

### PR DESCRIPTION
**Pull request by davekaro**
Found some empty characters in the seeds causing the parsing to fail.

Fixes https://github.com/codeforUV/food_resources/issues/39

### CODE REVIEW

**Review by thomascchen — APPROVED** [review]
👏

**Comment by davekaro** [comment]
Here is a better diff from my machine

diff

**Comment by bthooper** [comment]
it's weird...that space doesn't show up in my editor....

**Comment by davekaro** [comment]
Yeah - it's not really a space. It's some kind of unicode empty
character. It didn't show in my editor either, but I got it to output in

my rails console. I couldn't even get rid of it in my editor, I had to

create a new file and copy the lines in. I'm curious how you made the
file initially? Something injected extra stuff along the way

On October 22, 2020, GitHub <notifications@github.com> wrote:
> it's weird...that space doesn't show up in my editor....
>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/codeforUV/food_resources/pull/40#issuecomment-
714598994>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AAAFGD3U4YE33UEILPRXC7TSMBKLTANCNFSM4S3M7REA>.

**Comment by bthooper** [comment]
ah....weird...thanks...

I stupidly cut and copied some of that stuff directly from the VT food bank web site...so I must have got something that way...but weird that it didn't show up at all.....so sorry.

**Comment by davekaro** [comment]
No need to apologize! Very sneaky bug.

**Pull request merged**
